# Generated by Django 5.2.5 on 2025-09-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crucero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_crucero', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', help_text='Tipo de crucero', max_length=30)),
                ('codigo_identificacion', models.CharField(max_length=50, unique=True)),
                ('fecha_botadura', models.DateField()),
                ('fecha_adquisicion', models.DateField()),
                ('capacidad_pasajeros', models.PositiveIntegerField()),
                ('capacidad_tripulacion', models.PositiveIntegerField()),
                ('tonelaje', models.DecimalField(decimal_places=2, help_text='Toneladas de peso muerto', max_digits=10)),
                ('eslora', models.DecimalField(decimal_places=2, help_text='Longitud total (m)', max_digits=7)),
                ('manga', models.DecimalField(decimal_places=2, help_text='Ancho máximo (m)', max_digits=7)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura (m)', max_digits=7)),
                ('numero_cubiertas', models.PositiveIntegerField(default=0, help_text='Número de cubiertas')),
                ('bandera', models.CharField(max_length=50)),
                ('puerto_base', models.CharField(max_length=100)),
                ('estado_operativo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento'), ('viaje', 'En viaje')], default='activo', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción general del crucero')),
                ('modelo_motor', models.CharField(blank=True, max_length=100)),
                ('velocidad_maxima', models.DecimalField(decimal_places=2, help_text='Velocidad máxima en nudos', max_digits=6)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('tipo_combustible', models.CharField(choices=[('diesel', 'Diésel'), ('gasolina', 'Gasolina'), ('gnl', 'Gas Natural Licuado'), ('hibrido', 'Híbrido')], default='diesel', max_length=20)),
                ('consumo_combustible', models.DecimalField(blank=True, decimal_places=2, help_text='Consumo promedio en litros/hora', max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Crucero',
                'verbose_name_plural': 'Cruceros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FechaDelSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_dias', models.IntegerField(help_text='Duración total del ciclo de la ruta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de habitaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubierta', models.PositiveIntegerField(default=1, help_text='Número de cubierta')),
                ('codigo_ubicacion', models.CharField(blank=True, help_text='Código XXABC: XX=cubierta (2 dígitos), A=uso (2=rest.,3=bares/cafés,4=almacenes,5=entretenimiento,6=otros), BC=consecutivo (01-99)', max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('restaurantes', 'Restaurantes'), ('bares_cafes', 'Bares y Cafés'), ('almacen', 'Almacen'), ('entretenimiento', 'Sitios de Entretenimiento'), ('otro', 'Otro')], max_length=30)),
                ('capacidad', models.PositiveIntegerField(null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='cruceros.crucero')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EtapaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(help_text="Nombre del puerto o 'Navegación'", max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('dia_llegada', models.IntegerField(help_text='Día en que se llega a esta etapa')),
                ('tipo', models.CharField(choices=[('puerto', 'Puerto'), ('navegacion', 'Navegación')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='cruceros.ruta')),
            ],
            options={
                'ordering': ['dia_llegada'],
                'unique_together': {('ruta', 'dia_llegada')},
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubierta', models.PositiveIntegerField(help_text='Número de cubierta')),
                ('lado', models.CharField(choices=[('babor', 'Babor'), ('estribor', 'Estribor')], help_text='Lado del barco', max_length=10)),
                ('codigo_ubicacion', models.CharField(blank=True, help_text='Código UUAIII: UU=cubierta (2 dígitos), A=lado (0 babor / 1 estribor), III=consecutivo (001-999) por cubierta y lado', max_length=6)),
                ('numero', models.CharField(max_length=20)),
                ('ocupada', models.BooleanField(default=False)),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='cruceros.crucero')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='cruceros.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificacion', 'En Planificación'), ('activo', 'Activo'), ('completado', 'Completado')], default='planificacion', max_length=20)),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='cruceros.crucero')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruceros.ruta')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_actual', models.IntegerField(default=1)),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruceros.etaparuta')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual', to='cruceros.viaje')),
            ],
        ),
    ]
