services:
  - type: web
    name: django-cruise-bars-snacks
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Cruise-Services-ODYSSEY_-Bars-Snacks.wsgi:application
    autoDeploy: true
