services:
  - type: web
    name: django-cruise-bars-snacks
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn admin_project.wsgi:application
    autoDeploy: true
  