# Generated by Django 5.2.5 on 2025-09-05 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('cruceros', '0001_initial'),
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hora_aper', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion', models.ForeignKey(help_text='Ubicacion del bar dentro del crucero', on_delete=django.db.models.deletion.CASCADE, related_name='bares', to='cruceros.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientesReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('medida', models.CharField(choices=[('unidades', 'Unidades'), ('gramos', 'Gramos'), ('litros', 'Litros'), ('ml', 'Mililitros'), ('kg', 'Kilogramos')], default='unidades', max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_enrecetas', to='almacen.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('instruccion', models.CharField(max_length=800)),
                ('precio_vta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='bares_snacks.categoria', verbose_name='Categoría')),
                ('ingredientes', models.ManyToManyField(through='bares_snacks.IngredientesReceta', through_fields=('receta', 'producto'), to='almacen.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientesreceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_detalle', to='bares_snacks.menu'),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('lugar_consumo', models.CharField(default='Bar', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='bares_snacks.clientes')),
                ('empleado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_atendidos', to='recursos_humanos.personal')),
                ('ptoventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='bares_snacks.bar')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='bares_snacks.menu')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bares_snacks.pedidos')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.CheckConstraint(condition=models.Q(('hora_cierre__gt', models.F('hora_aper'))), name='hcierre_mayorqueapertura'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientesreceta',
            unique_together={('receta', 'producto')},
        ),
    ]
