# Generated by Django 5.2.5 on 2025-09-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=60)),
                ('tipo_almacen', models.CharField(max_length=40)),
                ('subtipo_almacen', models.CharField(max_length=40)),
                ('plan', models.CharField(choices=[('gratis', 'All Inclusive'), ('pago', 'Premium')], default='gratis', max_length=10)),
                ('receta', models.TextField(blank=True, default='')),
                ('precio_vta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
