# Generated by Django 5.2.5 on 2025-09-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0003_remove_pedidos_fecha'),
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='instalacion_consumo',
            field=models.ForeignKey(blank=True, help_text='Instalación física donde se consumirá (bar, restaurante, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_consumo', to='cruceros.instalacion'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='lugar_consumo',
            field=models.CharField(default='Bar', help_text='(LEGACY) Texto simple: Bar / Camarote. Reemplazar por instalacion_consumo.', max_length=20),
        ),
    ]
