# Generated by Django 5.2.5 on 2025-09-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0004_pedidos_instalacion_consumo_and_more'),
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='lugar_consumo',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='lugarentrega',
            field=models.ForeignKey(blank=True, help_text='Instalación física de entrega o consumo (bar, restaurante, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_entregados', to='cruceros.instalacion'),
        ),
    ]
