# Generated by Django 5.2.5 on 2025-09-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0014_drop_ingredientesreceta'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        # Actualiza sólo el estado de migración sin tocar la BD física (evita duplicar columnas ya creadas por RAW SQL previas)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='pedidos',
                    name='cliente',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ventas.cliente'),
                ),
                # Eliminar del estado el campo legacy 'menu' (ya removido en reconstrucciones previas de tabla)
                migrations.RemoveField(
                    model_name='detallepedido',
                    name='menu',
                ),
                # Añadir al estado el campo 'producto' (ya existe en BD por 0007/0012)
                migrations.AddField(
                    model_name='detallepedido',
                    name='producto',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='bares_snacks.productobar'),
                ),
                # Borrar del estado los modelos legacy (Clientes). IngredientesReceta se removerá en 0019
                migrations.DeleteModel(
                    name='Clientes',
                ),
            ]
        ),
    ]
