# Generated by Django 5.2.5 on 2025-09-06 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('bares_snacks', '0015_alter_pedidos_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unidad', models.CharField(blank=True, default='', max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_bares', to='almacen.producto')),
                ('producto_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_items', to='bares_snacks.productobar')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
                'unique_together': {('producto_bar', 'ingrediente')},
            },
        ),
    ]
