# Generated by Django 5.2.5 on 2025-09-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0016_ingredientereceta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='ptoventa',
        ),
    ]
