# Generated by Django 5.2.5 on 2025-09-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0017_remove_pedidos_ptoventa'),
        ('recursos_humanos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_atendidos', to='recursos_humanos.personal'),
        ),
    ]
