# Generated by Django 5.2.5 on 2025-09-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0019_remove_ingredientesreceta_state'),
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='habitacion',
            field=models.ForeignKey(blank=True, help_text='Habitación destino si el consumo es en camarote', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_servicio', to='cruceros.habitacion'),
        ),
    ]
