# Generated by Django 4.2.24 on 2025-09-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0020_pedidos_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Número de factura generado para el pedido (formato BR-XXX-0001[-PR])', max_length=32, null=True, unique=True),
        ),
    ]
