# Generated by Django 5.2.5 on 2025-09-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0005_remove_pedidos_lugar_consumo_pedidos_lugarentrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='instalacion_consumo',
        ),
    ]
