# Generated by Django 5.2.5 on 2025-09-05 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título de la actividad', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa de la actividad')),
                ('dia_crucero', models.IntegerField(choices=[(1, 'Día 1'), (2, 'Día 2'), (3, 'Día 3'), (4, 'Día 4'), (5, 'Día 5'), (6, 'Día 6'), (7, 'Día 7'), (8, 'Día 8')], help_text='Día del crucero (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('coste', models.DecimalField(decimal_places=2, help_text='Coste de la actividad en euros', max_digits=8)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la actividad')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización de la actividad')),
                ('maximoActividad', models.IntegerField(help_text='Número máximo de participantes')),
                ('img_src', models.CharField(blank=True, help_text='URL o ruta de la imagen de la actividad', max_length=500, null=True)),
                ('viaje', models.ForeignKey(blank=True, help_text='Viaje al que pertenece esta actividad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cruceros.viaje')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades_pago',
                'ordering': ['dia_crucero', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ActividadRutinaria',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título de la actividad rutinaria', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa de la actividad rutinaria')),
                ('dia_crucero', models.IntegerField(choices=[(1, 'Día 1'), (2, 'Día 2'), (3, 'Día 3'), (4, 'Día 4'), (5, 'Día 5'), (6, 'Día 6'), (7, 'Día 7'), (8, 'Día 8')], help_text='Día del crucero (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la actividad')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización de la actividad')),
                ('maximo_actividad', models.IntegerField(help_text='Número máximo de participantes')),
                ('ubicacion', models.CharField(help_text='Ubicación donde se realiza la actividad', max_length=200)),
                ('img_src', models.CharField(blank=True, help_text='URL o ruta de la imagen de la actividad', max_length=500, null=True)),
                ('viaje', models.ForeignKey(blank=True, help_text='Viaje al que pertenece esta actividad rutinaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_rutinarias', to='cruceros.viaje')),
            ],
            options={
                'verbose_name': 'Actividad Rutinaria',
                'verbose_name_plural': 'Actividades Rutinarias',
                'db_table': 'actividad_rutinaria',
                'ordering': ['dia_crucero', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividadPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100)),
                ('n_habitacion', models.CharField(help_text='Número de habitación del cliente', max_length=20)),
                ('n_personas', models.IntegerField(help_text='Número de personas incluidas en el registro')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total del pago', max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del registro', max_length=20)),
                ('id_factura', models.CharField(help_text='Identificador único de la factura', max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('viaje', models.ForeignKey(blank=True, help_text='Viaje asociado al registro de actividad de pago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_pago_actividades', to='cruceros.viaje')),
            ],
            options={
                'verbose_name': 'Registro de Actividad de Pago',
                'verbose_name_plural': 'Registros de Actividades de Pago',
                'db_table': 'registro_actividad_pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividadRut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100)),
                ('n_habitacion', models.CharField(help_text='Número de habitación del cliente', max_length=20)),
                ('n_personas', models.IntegerField(help_text='Número de personas incluidas en el registro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('viaje', models.ForeignKey(blank=True, help_text='Viaje asociado al registro de actividad rutinaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_rutinarios', to='cruceros.viaje')),
            ],
            options={
                'verbose_name': 'Registro de Actividad Rutinaria',
                'verbose_name_plural': 'Registros de Actividades Rutinarias',
                'db_table': 'registro_actividad_rut',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
