# Generated by Django 5.2.5 on 2025-09-05 04:27

import apps.cruceros.Services.fecha_general
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.IntegerField()),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('precio_lote', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField(default=apps.cruceros.Services.fecha_general.obtener_fecha_actual)),
                ('fecha_caducidad', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('tipo', models.CharField(choices=[('ALIMENTOS_FRESCOS', 'Alimentos Frescos'), ('ALIMENTOS_SECOS', 'Alimentos Secos'), ('BEBIDAS', 'Bebidas'), ('INSUMOS_COCINA', 'Insumos de Cocina'), ('LIMPIEZA', 'Limpieza'), ('SUMINISTROS_MEDICOS', 'Suministros Médicos'), ('MANTENIMIENTO', 'Materiales de Mantenimiento'), ('REPUESTOS_TECNICOS', 'Repuestos Técnicos'), ('EQUIPOS', 'Equipos'), ('TEXTILES', 'Textiles'), ('OFICINA', 'Oficina'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('SPA_GYM', 'SPA / GYM'), ('SEGURIDAD', 'Seguridad'), ('MERCHANDISING', 'Merchandising'), ('TECNOLOGIA', 'Tecnología')], max_length=25)),
                ('subtipo', models.CharField(blank=True, choices=[('FRUTA', 'Fruta'), ('VERDURA', 'Verdura'), ('CARNE', 'Carne'), ('PESCADO', 'Pescado'), ('MARISCO', 'Marisco'), ('LACTEOS', 'Lácteos'), ('PANIFICADOS', 'Panificados'), ('CHARCUTERIA', 'Charcutería'), ('CEREAL', 'Cereal'), ('PASTA', 'Pasta'), ('LEGUMINOSAS', 'Leguminosas'), ('ENLATADOS', 'Enlatados'), ('SNACKS', 'Snacks'), ('CONDIMENTOS', 'Condimentos'), ('AZUCAR_SAL', 'Azúcar / Sal'), ('AGUA', 'Agua'), ('REFRESCO', 'Refresco'), ('JUGO', 'Jugo'), ('ENERGETICA', 'Energética'), ('CAFE_TEA', 'Café / Té'), ('CERVEZA', 'Cerveza'), ('VINO', 'Vino'), ('DESTILADO', 'Destilado'), ('COCTEL_PREMEZCLA', 'Cóctel Premezclado'), ('DESCARTABLES', 'Descartables'), ('ENVASES', 'Envases'), ('UTENSILIOS', 'Utensilios'), ('GAS_COCINA', 'Gas Cocina'), ('HIELO', 'Hielo'), ('DETERGENTES', 'Detergentes'), ('DESINFECTANTES', 'Desinfectantes'), ('UTENSILIOS_LIMPIEZA', 'Utensilios Limpieza'), ('PAPEL_SANITARIO', 'Papel Sanitario'), ('AMBIENTADORES', 'Ambientadores'), ('MEDICAMENTO', 'Medicamento'), ('CURACION', 'Curación'), ('EQUIPO_DIAGNOSTICO', 'Equipo Diagnóstico'), ('EPP', 'Equipo Protección Personal'), ('INSTRUMENTAL', 'Instrumental'), ('SOLUCION_IV', 'Solución IV'), ('PINTURA', 'Pintura'), ('LUBRICANTE', 'Lubricante'), ('SELLADOR', 'Sellador'), ('ADHESIVO', 'Adhesivo'), ('ABRASIVO', 'Abrasivo'), ('FILTRO', 'Filtro'), ('ACEITE', 'Aceite'), ('MOTOR', 'Motor'), ('ELECTRICO', 'Eléctrico'), ('HVAC', 'HVAC'), ('NAVEGACION', 'Navegación'), ('ILUMINACION', 'Iluminación'), ('BOMBAS', 'Bombas'), ('VALVULAS', 'Válvulas'), ('ELECTRODOMESTICO', 'Electrodoméstico'), ('AUDIO_VIDEO', 'Audio / Video'), ('INFORMATICO', 'Informático'), ('GIMNASIO', 'Gimnasio'), ('COCINA_INDUSTRIAL', 'Cocina Industrial'), ('ROPA_CAMA', 'Ropa de Cama'), ('TOALLA', 'Toalla'), ('UNIFORME', 'Uniforme'), ('CORTINA', 'Cortina'), ('TAPICERIA', 'Tapicería'), ('PAPELERIA', 'Papelería'), ('IMPRESION', 'Impresión'), ('ESCRITORIO', 'Escritorio'), ('CONSUMIBLE_IT', 'Consumible IT'), ('JUEGO_MESA', 'Juego de Mesa'), ('JUEGO_VIDEO', 'Videojuego'), ('LIBRO_REVISTA', 'Libro / Revista'), ('EVENTO', 'Evento'), ('SONIDO_LUZ', 'Sonido / Luz'), ('COSMETICO', 'Cosmético'), ('ACEITE_MASAJE', 'Aceite de Masaje'), ('SUPLEMENTO', 'Suplemento'), ('ACC_FITNESS', 'Accesorio Fitness'), ('CHALECO_SALVAVIDAS', 'Chaleco Salvavidas'), ('EXTINTOR', 'Extintor'), ('SENALIZACION', 'Señalización'), ('ARNES', 'Arnés'), ('BOTIQUIN', 'Botiquín'), ('DETECTOR', 'Detector'), ('RECUERDO', 'Recuerdo'), ('PRENDA_LOGO', 'Prenda con Logo'), ('ACCESORIO_LOGO', 'Accesorio con Logo'), ('BEBIDA_PREMIUM', 'Bebida Premium'), ('DULCE_GOURMET', 'Dulce Gourmet'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('CABLEADO', 'Cableado'), ('CAMARA_SEGURIDAD', 'Cámara de Seguridad'), ('SENSOR', 'Sensor'), ('DISPOSITIVO_PORTATIL', 'Dispositivo Portátil')], max_length=25, null=True)),
                ('cantidad_ideal', models.PositiveIntegerField()),
                ('medida', models.CharField(choices=[('L', 'Litros'), ('M', 'Metros'), ('K', 'Kilogramos'), ('U', 'Unidades')], max_length=1)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('precio_lote', models.PositiveIntegerField(help_text='Precio total esperado del lote')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('POR_REGISTRAR', 'Por registrar')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateField(default=apps.cruceros.Services.fecha_general.obtener_fecha_actual)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='almacen.producto')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('NEW', 'Creado'), ('MERMA', 'Merma')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=apps.cruceros.Services.fecha_general.obtener_fecha_actual)),
                ('modulo', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('BARES_SNACKS', 'Bares Snacks'), ('MANTENIMIENTO', 'Mantenimiento'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('RESERVACIONES', 'Reservaciones'), ('ALMACEN', 'Almacén'), ('SERVICIO_MEDICO', 'Servicio Médico'), ('ADMINISTRACION', 'Administración'), ('FUERA_BARCO', 'Fuera del Barco')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='almacen.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='almacen.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Producto',
                'verbose_name_plural': 'Movimientos de Producto',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='almacen.producto'),
        ),
        migrations.CreateModel(
            name='SeccionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('REFRIGERACION', 'Cámara de Refrigeración'), ('CONGELACION', 'Cámara de Congelación'), ('SECO', 'Almacén Seco'), ('ESTANTERIAS', 'Estanterías'), ('CUARTO_FRIO', 'Cuarto Frío'), ('SILOS', 'Silos'), ('TANQUES', 'Tanques')], max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(limit_choices_to={'tipo': 'almacen'}, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='cruceros.instalacion')),
            ],
            options={
                'verbose_name': 'Sección de Almacén',
                'verbose_name_plural': 'Secciones de Almacén',
                'unique_together': {('almacen', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='almacen.seccionalmacen'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('producto', 'numero_lote')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo', 'subtipo'], name='indice_producto_tipo_subtipo'),
        ),
    ]
